<?php

namespace MakinMind\ProjectBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DomainsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomainsRepository extends EntityRepository
{
}