<?php

namespace MakinMind\ProjectBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PartnersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartnersRepository extends EntityRepository
{
}