<?php

namespace MakinMind\ProjectBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{

	public function getMyprojects (User $user) {
		$query = $em->createQuery("SELECT p FROM MakinMind\ProjectBundle\Entity\Project p WHERE p.owner = ?1 OR p IN (SELECT proj FROM MakinMind\ProjectBundle\Entity\Partners part JOIN part.project proj WHERE part.partner = ?1)");
		$query->setParameter(1, $user);
	}
}