<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class MakinMindProjectBundleEntityContractProxy extends \MakinMind\ProjectBundle\Entity\Contract implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setCreaDate($creaDate)
    {
        $this->__load();
        return parent::setCreaDate($creaDate);
    }

    public function getCreaDate()
    {
        $this->__load();
        return parent::getCreaDate();
    }

    public function setSignDate($signDate)
    {
        $this->__load();
        return parent::setSignDate($signDate);
    }

    public function getSignDate()
    {
        $this->__load();
        return parent::getSignDate();
    }

    public function setAmount($amount)
    {
        $this->__load();
        return parent::setAmount($amount);
    }

    public function getAmount()
    {
        $this->__load();
        return parent::getAmount();
    }

    public function setStatus($status)
    {
        $this->__load();
        return parent::setStatus($status);
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function setProject(\MakinMind\ProjectBundle\Entity\Project $project)
    {
        $this->__load();
        return parent::setProject($project);
    }

    public function getProject()
    {
        $this->__load();
        return parent::getProject();
    }

    public function setWorker(\MakinMind\UserBundle\Entity\User $worker)
    {
        $this->__load();
        return parent::setWorker($worker);
    }

    public function getWorker()
    {
        $this->__load();
        return parent::getWorker();
    }

    public function setStandardized(\MakinMind\ProjectBundle\Entity\ContractTypes $standardized)
    {
        $this->__load();
        return parent::setStandardized($standardized);
    }

    public function getStandardized()
    {
        $this->__load();
        return parent::getStandardized();
    }

    public function setCustomized(\MakinMind\ResourceBundle\Entity\Resource $customized)
    {
        $this->__load();
        return parent::setCustomized($customized);
    }

    public function getCustomized()
    {
        $this->__load();
        return parent::getCustomized();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'creaDate', 'signDate', 'amount', 'status', 'project', 'worker', 'standardized', 'customized');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}